apiVersion: v2
name: rancher-devops-operator
description: A Kubernetes operator for managing Rancher projects and namespaces
type: application
version: 0.1.3
appVersion: 0.1.3
keywords:
  - rancher
  - operator
  - devops
  - kubernetes
maintainers:
  - name: DevOps Team
icon: https://raw.githubusercontent.com/Jasonrve/rancher-devops-operator/main/resources/images/project-icon-transparent.png
