apiVersion: v2
name: rancher-devops-operator
description: A Kubernetes operator for managing Rancher projects and namespaces
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - rancher
  - operator
  - devops
  - kubernetes
maintainers:
  - name: DevOps Team
