apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rancher-devops-operator.fullname" . }}
  labels:
    {{- include "rancher-devops-operator.labels" . | nindent 4 }}
rules:
  # Permissions for RancherProject CRD
  - apiGroups:
      - rancher.devops.io
    resources:
      - rancherprojects
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rancher.devops.io
    resources:
      - rancherprojects/status
    verbs:
      - get
      - update
      - patch
  # Permissions for events
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # Permissions to read ConfigMaps and Secrets
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  # Permissions for leader election
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
