{{- if not .Values.rancher.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-devops-operator.fullname" . }}-rancher
  labels:
    {{- include "rancher-devops-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.rancher.token }}
  token: {{ .Values.rancher.token | quote }}
  {{- end }}
  {{- if .Values.rancher.username }}
  username: {{ .Values.rancher.username | quote }}
  {{- end }}
  {{- if .Values.rancher.password }}
  password: {{ .Values.rancher.password | quote }}
  {{- end }}
{{- end }}
